### ISSUE TITLE
Production Server 구축

### ISSUE THREAD

**Issue by minnnisu** [Team-MansuMugang/mansumugang-backend#106]
Production Server를 구축하도록 하겠습니다.
개발 내용은 다음과 같습니다,

**Task**

- [x] EC2 생성
- [x] Nginx 구성
- [x] 도커를 이용하여 Spring Boot App, MySQL, Redis 컨테이너화
- [x] AWS S3, Code Deploy, Github Actions를 활용하여 무중단 CI/CD 구축
- [ ] AWS S3를 사용하여 정적 파일 관리(이미지, 오디오 등)
- [x] HTTPS 적용
