### ISSUE TITLE
약 미복용 환자 관리 기능 구현

### ISSUE THREAD

**Issue by minnnisu** [Team-MansuMugang/mansumugang-backend#57]
약 미복용 환자 관리 기능을 구현하도록 하겠습니다.
구현할 내용은 아래와 같습니다.

**Task**
- [x] Spring Scheduler를 이용하여 주기적으로 약 미복용 환자 탐색
- [x] 미복용 환자의 상태 변경(WAITING -> PASS)
- [x] MedicineCommonService의 상태 배정 메소드에 대한 주석 추가
