### ISSUE TITLE
환자의 병원 방문 일정관리 기능 구현

### ISSUE THREAD

**Issue by minnnisu** [Team-MansuMugang/mansumugang-backend#71]
환자의 병원 방문 일정관리 기능을 구현하고자 합니다.
구현할 기능들은 다음과 같습니다.

**Task**
- [x] 병원 방문일정 조회(날짜 조회, 상세정보 조회)
- [x] 병원 방문일정 등록
- [x] 병원 방문일정 수정
- [x] 병원 방문일정 삭제
- [x] 특정일 병원 일정 조회 기능 구현
- [x] 일정 토글 기능

날짜 조회 시 기존의 약 일정과 함께 보여질 수 있도록 약 조회의 스펙 또한 변경될 예정입니다.
