### ISSUE TITLE
약 토글기능 스펙 변경

### ISSUE THREAD

**Issue by minnnisu** [Team-MansuMugang/mansumugang-backend#72]
약 토글기능에 대한 스펙 변경을 하고자 합니다.
기존의 토글기능에는 한번에 하나의 약에 대한 상태만 변경이 가능했습니다.
프론트엔드와 논의한 결과 한번에 여러 개의 약에 대한 리스트를 받아서 상태 변경이 가능하도록 만들기로 결정하였습니다.
구현할 내용은 다음과 같습니다.

**Task**

- [x] 토글 시 한번에 여러 개의 약에 대한 리스트를 받아서 상태 변경이 가능하도록 스펙 변경
- [x] Inner Class을 사용한 Dto로 리펙토링
- [x] 실제 약 복용시간 로직 수정
